Repository dnd-side-project/dnd-8th-2-frontend, pull requests merged in 2023-02, with the labels that each got.

#2 FEAT: System button
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Enum/AssetColors.swift
  Reet-Place/Reet-Place/Global/Protocols/ButtonActiveColorProvider.swift
  Reet-Place/Reet-Place/Global/Protocols/ButtonDefaultColorProvider.swift
  Reet-Place/Reet-Place/Global/Protocols/ButtonDisabledColorProvider.swift
  Reet-Place/Reet-Place/Screen/MyPage/ViewController/MyPageVC.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetButton/ReetButton.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetButton/ReetButtonStyle.swift
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Common/Black.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Common/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Common/White.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Error/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Error/Error.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray100.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray200.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray300.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray400.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray50.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray500.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray600.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray700.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray800.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Gray/Gray900.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary100.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary200.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary300.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary400.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary50.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary500.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary600.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary700.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary800.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Primary/Primary900.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Success/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Success/Success.colorset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Warning/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Colors/Warning/Warning.colorset/Contents.json
Labels: Feature

#7 [FEAT] 폰트 / 색상 지정
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Class/BaseLabel.swift
  Reet-Place/Reet-Place/Global/Class/BaseVerticalScrollViewController.swift
  Reet-Place/Reet-Place/Global/Class/BaseViewController.swift
  Reet-Place/Reet-Place/Global/Enum/AssetFonts.swift
  Reet-Place/Reet-Place/Global/Extension/NSMutableAttributedString+.swift
  Reet-Place/Reet-Place/Global/Extension/String+Ext.swift
  Reet-Place/Reet-Place/Global/Font/Pretendard-Bold.otf
  Reet-Place/Reet-Place/Global/Font/Pretendard-Regular.otf
  Reet-Place/Reet-Place/Screen/MyPage/ViewController/MyPageVC.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetButton/ReetButton.swift
  Reet-Place/Reet-Place/Support/Info.plist
Labels: Feature, Refactoring

#8 [FEAT] 마이페이지 Boilerplate
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Assets/AssetColors.swift
  Reet-Place/Reet-Place/Global/Assets/AssetFonts.swift
  Reet-Place/Reet-Place/Global/Assets/AssetsImages.swift
  Reet-Place/Reet-Place/Global/Assets/en.lproj/Localizable.strings
  Reet-Place/Reet-Place/Global/Class/BaseLabel.swift
  Reet-Place/Reet-Place/Global/Class/BaseNavigationViewController.swift
  Reet-Place/Reet-Place/Global/Class/BaseViewController.swift
  Reet-Place/Reet-Place/Global/Datasource/MyPageMenuDataSource.swift
  Reet-Place/Reet-Place/Global/Enum/AssetsImages.swift
  Reet-Place/Reet-Place/Global/Extension/NSMutableAttributedString+.swift
  Reet-Place/Reet-Place/Global/Extension/String+Ext.swift
  Reet-Place/Reet-Place/Global/Extension/UIViewController+.swift
  Reet-Place/Reet-Place/Global/Network/APISession.swift
  Reet-Place/Reet-Place/Global/Protocols/ForegroundColorProvider.swift
  Reet-Place/Reet-Place/Global/Service/Service.swift
  Reet-Place/Reet-Place/Global/Utils/KeychainManager.swift
  Reet-Place/Reet-Place/Screen/MyPage/Model/MyPageMenu.swift
  Reet-Place/Reet-Place/Screen/MyPage/View/LoginView.swift
  Reet-Place/Reet-Place/Screen/MyPage/ViewController/MyPageVC.swift
  Reet-Place/Reet-Place/Screen/MyPage/ViewModel/MyPageViewModel.swift
  Reet-Place/Reet-Place/Screen/Share/TableViewCell/DefaultCategoryTVC.swift
  Reet-Place/Reet-Place/Screen/Share/View/NavigationBar.swift
  Reet-Place/Reet-Place/Screen/TabBar/ReetPlaceTBC.swift
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Cancel48.imageset/Cancel.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Cancel48.imageset/Cancel@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Cancel48.imageset/Cancel@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Cancel48.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronLeft48.imageset/ChevronLeft.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronLeft48.imageset/ChevronLeft@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronLeft48.imageset/ChevronLeft@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronLeft48.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight24.imageset/ChevronRight.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight24.imageset/ChevronRight@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight24.imageset/ChevronRight@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight24.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight52.imageset/ChevronRight52.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight52.imageset/ChevronRight52@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight52.imageset/ChevronRight52@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight52.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Contents.json
Labels: 마이페이지, View, Feature, 로그인 / 회원가입

#9 [FEAT] Implement profile view
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Assets/AssetsImages.swift
  Reet-Place/Reet-Place/Global/Extension/String+Ext.swift
  Reet-Place/Reet-Place/Global/Model/ModelUser.swift
  Reet-Place/Reet-Place/Screen/MyPage/ViewController/MyPageVC.swift
  Reet-Place/Reet-Place/Screen/MyPage/ViewModel/MyPageViewModel.swift
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ProfilePlaceholder.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ProfilePlaceholder.imageset/ProfilePlaceholder.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ProfilePlaceholder.imageset/ProfilePlaceholder@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ProfilePlaceholder.imageset/ProfilePlaceholder@3x.png
Labels: Feature

#10 [FEAT] : Implement user info
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Assets/AssetsImages.swift
  Reet-Place/Reet-Place/Global/Assets/en.lproj/Localizable.strings
  Reet-Place/Reet-Place/Global/Class/BaseNavigationViewController.swift
  Reet-Place/Reet-Place/Global/Datasource/UserInfoMenuDataSource.swift
  Reet-Place/Reet-Place/Global/Enum/AccountProviderType.swift
  Reet-Place/Reet-Place/Global/Model/ModelUser.swift
  Reet-Place/Reet-Place/Global/Protocols/IconProvider.swift
  Reet-Place/Reet-Place/Screen/MyPage/ViewController/MyPageVC.swift
  Reet-Place/Reet-Place/Screen/MyPage/ViewModel/MyPageViewModel.swift
  Reet-Place/Reet-Place/Screen/Share/TableViewCell/DefaultCategoryTVC.swift
  Reet-Place/Reet-Place/Screen/UserInfo/Model/UserInfoMenu.swift
  Reet-Place/Reet-Place/Screen/UserInfo/TableViewCell/UserInfoTVC.swift
  Reet-Place/Reet-Place/Screen/UserInfo/ViewController/UserInfoVC.swift
  Reet-Place/Reet-Place/Screen/UserInfo/ViewModel/UserInfoViewModel.swift
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Kakao.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Kakao.imageset/kakao.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Kakao.imageset/kakao@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Kakao.imageset/kakao@3x.png
Labels: 마이페이지, Feature

#11 [FIX] Create .gitaatributes & UserProfileView
  .gitattributes
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Screen/MyPage/View/UserProfileView.swift
Labels: bug🐞

#12 Feat/#6 북마크 탭 레이아웃 구성
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place.xcodeproj/xcshareddata/xcschemes/Reet-Place.xcscheme
  Reet-Place/Reet-Place/Global/Class/BaseAttributedLabel.swift
  Reet-Place/Reet-Place/Screen/BookMark/Cell/BookmarkTypeCVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/AllBookmarkButton.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/EmptyBookmarkView.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/RequestLoginView.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkAllVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkHistoryVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkWishlistVC.swift
  Reet-Place/Reet-Place/Screen/MyPage/View/LoginView.swift
  Reet-Place/Reet-Place/Screen/MyPage/View/UserProfileView.swift
  Reet-Place/Reet-Place/Screen/Share/TableViewCell/DefaultCategoryTVC.swift
  Reet-Place/Reet-Place/Screen/Share/View/NavigationBar.swift
  Reet-Place/Reet-Place/Screen/UserInfo/TableViewCell/UserInfoTVC.swift
Labels: 북마크, View, Feature, 태현

#14 Feat/#5 네이버 지도 추가
  Reet-Place/Podfile
  Reet-Place/Podfile.lock
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Screen/Home/ViewController/HomeVC.swift
  Reet-Place/Reet-Place/Screen/Map/ViewController/MapVC.swift
  Reet-Place/Reet-Place/Screen/TabBar/ReetPlaceTBC.swift
  Reet-Place/Reet-Place/Support/Info.plist
Labels: 홈, View, Feature, 희재

#15 Feat/#13 북마크 Type 선택 시 화면 구현, FAB 구현
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Assets/AssetsImages.swift
  Reet-Place/Reet-Place/Screen/BookMark/Cell/BookmarkCardTVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkCardModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/AllBookmarkButton.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/BookmarkFilterView.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/RelatedUrlButton.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/WithPeopleView.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkAllVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkHistoryVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkWishlistVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewModel/BookmarkCardListVM.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetFAB/ReetFAB.swift
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardHistoryChip20.imageset/CardHistoryChip20.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardHistoryChip20.imageset/CardHistoryChip20@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardHistoryChip20.imageset/CardHistoryChip20@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardHistoryChip20.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardMenu24.imageset/CardMenu24.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardMenu24.imageset/CardMenu24@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardMenu24.imageset/CardMenu24@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardMenu24.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardThreeStar14.imageset/CardThreeStar14.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardThreeStar14.imageset/CardThreeStar14@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardThreeStar14.imageset/CardThreeStar14@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardThreeStar14.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardTwoStar14.imageset/CardTwoStar14.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardTwoStar14.imageset/CardTwoStar14@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardTwoStar14.imageset/CardTwoStar14@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardTwoStar14.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardWishChip20.imageset/CardWishChip20.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardWishChip20.imageset/CardWishChip20@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardWishChip20.imageset/CardWishChip20@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/CardWishChip20.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight28.imageset/ChevronRight28.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight28.imageset/ChevronRight28@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight28.imageset/ChevronRight28@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ChevronRight28.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/DirectionTool20.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/DirectionTool20.imageset/DirectionTool20.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/DirectionTool20.imageset/DirectionTool20@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/DirectionTool20.imageset/DirectionTool20@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ExpandLess16.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ExpandLess16.imageset/ExpandLess16.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ExpandLess16.imageset/ExpandLess16@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ExpandLess16.imageset/ExpandLess16@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ExpandMore16.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ExpandMore16.imageset/ExpandMore16.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ExpandMore16.imageset/ExpandMore16@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/ExpandMore16.imageset/ExpandMore16@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Filter16.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Filter16.imageset/Filter16.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Filter16.imageset/Filter16@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Filter16.imageset/Filter16@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Map20.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Map20.imageset/Map20.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Map20.imageset/Map20@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Map20.imageset/Map20@3x.png
Labels: 북마크, View, Feature, 태현
