Repository dnd-side-project/dnd-8th-2-frontend, pull requests merged in 2023-12, with the labels that each got.

#76 Feat/#75 북마크 탭 바텀시트 서버 연결
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Enum/BookmarkSearchType.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkCardModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkModifyRequestModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/BookmarkBottomSheet/SelectTypeButton.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/BookmarkBottomSheet/StarToggleButton.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkAllVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkBottomSheetVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkHistoryVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkWishlistVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewModel/BookmarkBottomSheetVM.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewModel/BookmarkCardListVM.swift
  Reet-Place/Reet-Place/Screen/Shared/View/PlaceInfoView.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetPopUp/ReetPopUp.swift
Labels: 북마크, Network, 태현

#78 Feat/#60 키워드로 장소검색 서버연결
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Assets/AssetsImages.swift
  Reet-Place/Reet-Place/Global/Assets/en.lproj/Localizable.strings
  Reet-Place/Reet-Place/Global/Datasource/SearchResultDataSource.swift
  Reet-Place/Reet-Place/Global/Extension/UIImageView+.swift
  Reet-Place/Reet-Place/Global/Extension/UIView+.swift
  Reet-Place/Reet-Place/Global/Protocols/BookmarkCardAction.swift
  Reet-Place/Reet-Place/Screen/BookMark/Cell/BookmarkCardTVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/Cell/BookmarkTypeCVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/Cell/SearchResultTVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/Model/SearchPlaceKeywordRequestModel.swift
  Reet-Place/Reet-Place/Screen/Home/Search/Model/SearchPlaceKeywordResponseModel.swift
  Reet-Place/Reet-Place/Screen/Home/Search/ViewController/SearchVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/ViewModel/SearchVM.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/HomeVC.swift
  Reet-Place/Reet-Place/Screen/Shared/View/PlaceInfoView.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetFAB/ReetFABImage.swift
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Home/Search/GoToTop.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Home/Search/GoToTop.imageset/ExpandLess@1x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Home/Search/GoToTop.imageset/ExpandLess@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Home/Search/GoToTop.imageset/ExpandLess@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Home/Search/PlaceResultThumbnail.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Home/Search/PlaceResultThumbnail.imageset/PlaceResultThumbnail@1x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Home/Search/PlaceResultThumbnail.imageset/PlaceResultThumbnail@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Home/Search/PlaceResultThumbnail.imageset/PlaceResultThumbnail@3x.png
Labels: 홈, Network, 희재

#83 Feat/#72 북마크탭 지도로 보기 연결
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Enum/BookmarkSearchType.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkSummaryModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkSummaryResponseModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkAllVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkHistoryVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkMapVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkWishlistVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewModel/BookmarkMapVM.swift
Labels: 북마크, View, Network, Feature, 태현

#84 Chore/#79 탈퇴 사유 다중 선택 가능 수정
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/Model/DeleteAccountModel.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/Model/DeleteAccountRequestModel.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/View/CheckboxButton.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/ViewController/DeleteAccountVC.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/ViewModel/DeleteAccountVM.swift
Labels: Network, 태현, 로그인 / 회원가입, Chore

#85 Feat/#80 북마크 생성 연결
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Assets/AssetsImages.swift
  Reet-Place/Reet-Place/Global/Assets/en.lproj/Localizable.strings
  Reet-Place/Reet-Place/Global/Extension/UIImageView+.swift
  Reet-Place/Reet-Place/Screen/BookMark/Cell/BookmarkCardTVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/Cell/BookmarkTypeCVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkCardModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkListResponseModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkSaveRequestModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkSummaryModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkSummaryResponseModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/View/BookmarkBottomSheet/StarToggleButton.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkAllVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkBottomSheetVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkHistoryVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkMapVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkWishlistVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewModel/BookmarkBottomSheetVM.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewModel/BookmarkCardListVM.swift
  Reet-Place/Reet-Place/Screen/Home/Model/SearchPlaceListResponseModel.swift
  Reet-Place/Reet-Place/Screen/Home/Search/Model/SearchPlaceKeywordResponseModel.swift
  Reet-Place/Reet-Place/Screen/Home/Search/ViewController/SearchVC.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/HomeVC.swift
  Reet-Place/Reet-Place/Screen/Shared/View/PlaceInfoView.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetBottomSheet/PlaceBottomSheet.swift
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/BottomSheet/StarFolder.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/BottomSheet/StarFolder.imageset/StarFolder.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/BottomSheet/StarFolder.imageset/StarFolder@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/BottomSheet/StarFolder.imageset/StarFolder@3x.png
Labels: 북마크, Network, Feature, 태현
