Repository dnd-side-project/dnd-8th-2-frontend, pull requests merged in 2023-08, with the labels that each got.

#57 Feat/#55 카카오 로그인 구현 및 서버연결
  Reet-Place/Podfile
  Reet-Place/Podfile.lock
  Reet-Place/Reet-Place/Global/Assets/AssetsImages.swift
  Reet-Place/Reet-Place/Global/Enum/LoginType.swift
  Reet-Place/Reet-Place/Screen/Login/View/LoginButton.swift
  Reet-Place/Reet-Place/Screen/Login/ViewController/LoginVC.swift
  Reet-Place/Reet-Place/Screen/Login/ViewModel/LoginVM.swift
  Reet-Place/Reet-Place/Support/AppDelegate.swift
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/MyPage/AppleWhiteLogoOnly.imageset/AppleWhiteLogoOnly@1x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/MyPage/AppleWhiteLogoOnly.imageset/AppleWhiteLogoOnly@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/MyPage/AppleWhiteLogoOnly.imageset/AppleWhiteLogoOnly@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/MyPage/AppleWhiteLogoOnly.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/MyPage/KakaoLogin.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/MyPage/KakaoLogin.imageset/KakaoLogin@1x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/MyPage/KakaoLogin.imageset/KakaoLogin@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/MyPage/KakaoLogin.imageset/KakaoLogin@3x.png
  Reet-Place/Reet-Place/Support/Info.plist
  Reet-Place/Reet-Place/Support/SceneDelegate.swift
Labels: Network, Feature, 희재, 로그인 / 회원가입

#67 Fix/#66 Light Mode 설정
  Reet-Place/Reet-Place/Support/Info.plist
Labels: bug🐞, View, 태현, Chore

#63 Feat/#62 탈퇴 기능 서버 연결, 로그인, 온보딩, 메인 화면 분기 처리
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Assets/AssetsImages.swift
  Reet-Place/Reet-Place/Global/Assets/en.lproj/Localizable.strings
  Reet-Place/Reet-Place/Global/Enum/DeleteAccountSurveyType.swift
  Reet-Place/Reet-Place/Global/Network/APIService.swift
  Reet-Place/Reet-Place/Global/Network/APISession.swift
  Reet-Place/Reet-Place/Global/Utils/KeychainManager.swift
  Reet-Place/Reet-Place/Screen/Login/ViewController/LoginVC.swift
  Reet-Place/Reet-Place/Screen/Login/ViewModel/LoginVM.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/Model/DeleteAccountRequestModel.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/ViewController/AccountDeletedVC.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/ViewController/DeleteAccountVC.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/ViewModel/DeleteAccountVM.swift
  Reet-Place/Reet-Place/Screen/MyPage/ViewModel/MyPageVM.swift
  Reet-Place/Reet-Place/Screen/Shared/View/Onboarding/FirstTypeOnboardingView.swift
  Reet-Place/Reet-Place/Screen/Shared/View/Onboarding/OnboardingVC.swift
  Reet-Place/Reet-Place/Screen/Shared/View/Onboarding/OnboardingView.swift
  Reet-Place/Reet-Place/Screen/Shared/View/Onboarding/OtherTypeOnboardingView.swift
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/Cancel44.imageset/Cancel44.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/Cancel44.imageset/Cancel44@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/Cancel44.imageset/Cancel44@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/Cancel44.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingFirst.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingFirst.imageset/OnboardingFirst.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingFirst.imageset/OnboardingFirst@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingFirst.imageset/OnboardingFirst@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingFourth.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingFourth.imageset/OnboardingFourth.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingFourth.imageset/OnboardingFourth@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingFourth.imageset/OnboardingFourth@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingSecond.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingSecond.imageset/OnboardingSecond.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingSecond.imageset/OnboardingSecond@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingSecond.imageset/OnboardingSecond@3x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingThird.imageset/Contents.json
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingThird.imageset/OnboardingThird.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingThird.imageset/OnboardingThird@2x.png
  Reet-Place/Reet-Place/Support/Assets.xcassets/Images/Onboarding/OnboardingThird.imageset/OnboardingThird@3x.png
  Reet-Place/Reet-Place/Support/SceneDelegate.swift
Labels: View, Network, Feature, 태현, 로그인 / 회원가입
