Repository dnd-side-project/dnd-8th-2-frontend, pull requests merged in 2024-02, with the labels that each got.

#111 Feat/#99 더보기 버튼 -> 링크복사 기능
  Reet-Place/Reet-Place/Global/Assets/en.lproj/Localizable.strings
  Reet-Place/Reet-Place/Global/Extension/UIViewController+.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkCardModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkListResponseModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/Model/BookmarkSummaryModel.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkBottomSheetVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkListVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/ViewController/SearchVC.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/ViewController/DeleteAccountVC.swift
  Reet-Place/Reet-Place/Screen/Shared/View/PlaceInfoView.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetSelectBox/SelectBoxStyle.swift
Labels: View, Feature, 태현

#112 Feat/#95 위치 조회 로직 수정, 사용자 위치 노출
  Reet-Place/Podfile.lock
  Reet-Place/Reet-Place/Screen/Home/Search/ViewController/SearchVC.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/HomeVC.swift
Labels: bug🐞, Feature, 태현

#120 Feat/#98 사용자가 검색한 키워드 기록 및 조회 기능 구현
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/CoreData/CoreDataManager.swift
  Reet-Place/Reet-Place/Global/CoreData/ReetPlace.xcdatamodeld/ReetPlace.xcdatamodel/contents
  Reet-Place/Reet-Place/Global/CoreData/SearchHistory+CoreDataClass.swift
  Reet-Place/Reet-Place/Global/CoreData/SearchHistory+CoreDataProperties.swift
  Reet-Place/Reet-Place/Global/Datasource/KeywordHistoryDataSource.swift
  Reet-Place/Reet-Place/Global/Enum/CoreDataEntityList.swift
  Reet-Place/Reet-Place/Global/Enum/TabPlaceCategoryList.swift
  Reet-Place/Reet-Place/Global/Network/APIService.swift
  Reet-Place/Reet-Place/Global/Network/APISession.swift
  Reet-Place/Reet-Place/Global/Protocols/SearchHistoryAction.swift
  Reet-Place/Reet-Place/Global/Protocols/SearchHistoryListAction.swift
  Reet-Place/Reet-Place/Screen/Home/Cell/PlaceResultListCVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/Cell/SearchHistoryListCVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/Cell/SearchHistoryTVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/Model/SearchHistoryResponseModel.swift
  Reet-Place/Reet-Place/Screen/Home/Search/ViewController/SearchVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/ViewModel/SearchVM.swift
  Reet-Place/Reet-Place/Screen/Home/ViewModel/HomeVM.swift
Labels: View, Network, Feature, 희재, 검색

#126 Fix/#121 TestFlight 배포 시 애플 로그인이 작동하지 않는 문제 해결
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Reet-PlaceRelease.entitlements
Labels: bug🐞, 태현, 로그인 / 회원가입

#128 Chore/#124 홈 화면 첫 진입 시 현재 위치를 기본 값으로 설정
  Reet-Place/Reet-Place/Screen/Home/ViewController/HomeVC.swift
Labels: 홈, 태현, Chore

#127 Fix/#123 비 로그인 상태에서 "북마크 저장하기" 기능 제어
  Reet-Place/Reet-Place/Global/Assets/en.lproj/Localizable.strings
  Reet-Place/Reet-Place/Global/Enum/PopUpType.swift
  Reet-Place/Reet-Place/Screen/Home/Search/ViewController/SearchVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/ViewModel/SearchVM.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetBottomSheet/PlaceBottomSheet.swift
Labels: bug🐞, 북마크, 태현

#132 chore/#125 홈화면 최초 진입 시 '릿플인기' 카테고리 기본 선택
  Reet-Place/Reet-Place/Screen/Home/ViewController/HomeVC.swift
Labels: 홈, 희재, Chore
