Repository dnd-side-project/dnd-8th-2-frontend, pull requests merged in 2024-01, with the labels that each got.

#87 Feat/#86 Fastlane을 통한 인증서 관리, testFlight 배포 자동화
  .gitignore
  Reet-Place/Gemfile
  Reet-Place/Gemfile.lock
  Reet-Place/Podfile.lock
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/fastlane/Appfile
  Reet-Place/fastlane/Devicefile
  Reet-Place/fastlane/Fastfile
  Reet-Place/fastlane/Matchfile
  Reet-Place/fastlane/README.md
  Reet-Place/fastlane/key.json
Labels: Refactoring, 태현

#89 Refactoring/#88 카테고리 필터 바텀시트 구현방식 변경
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/Datasource/CategoryDetail/CategoryDetailActivityDataSource.swift
  Reet-Place/Reet-Place/Global/Datasource/CategoryDetail/CategoryDetailCafeDataSource.swift
  Reet-Place/Reet-Place/Global/Datasource/CategoryDetail/CategoryDetailCultureDataSource.swift
  Reet-Place/Reet-Place/Global/Datasource/CategoryDetail/CategoryDetailFoodDataSource.swift
  Reet-Place/Reet-Place/Global/Datasource/CategoryDetail/CategoryDetailPhotoBoothDataSource.swift
  Reet-Place/Reet-Place/Global/Datasource/CategoryDetail/CategoryDetailShoppingDataSource.swift
  Reet-Place/Reet-Place/Global/Datasource/CategoryDetailDataSource.swift
  Reet-Place/Reet-Place/Global/Datasource/CategoryDetailListDataSource.swift
  Reet-Place/Reet-Place/Global/Enum/CategoryDetail/CategoryDetailActivityList.swift
  Reet-Place/Reet-Place/Global/Enum/CategoryDetail/CategoryDetailBarList.swift
  Reet-Place/Reet-Place/Global/Enum/CategoryDetail/CategoryDetailCafeList.swift
  Reet-Place/Reet-Place/Global/Enum/CategoryDetail/CategoryDetailCultureList.swift
  Reet-Place/Reet-Place/Global/Enum/CategoryDetail/CategoryDetailFoodList.swift
  Reet-Place/Reet-Place/Global/Enum/CategoryDetail/CategoryDetailPhotoBoothList.swift
  Reet-Place/Reet-Place/Global/Enum/CategoryDetail/CategoryDetailRestaurantList.swift
  Reet-Place/Reet-Place/Global/Enum/CategoryDetail/CategoryDetailShoppingList.swift
  Reet-Place/Reet-Place/Global/Enum/PlaceCategoryList.swift
  Reet-Place/Reet-Place/Global/Enum/TabPlaceCategoryList.swift
  Reet-Place/Reet-Place/Screen/Home/Cell/CategoryDetailListCVC.swift
  Reet-Place/Reet-Place/Screen/Home/Cell/CategoryFilterCVC.swift
  Reet-Place/Reet-Place/Screen/Home/Cell/DetailCategoryChipCVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/Cell/SearchHistoryListCVC.swift
  Reet-Place/Reet-Place/Screen/Home/Search/ViewController/SearchVC.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/CategoryBottomSheet/CategoryDetailCollectionView/CategoryDetailActivityView.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/CategoryBottomSheet/CategoryDetailCollectionView/CategoryDetailCafeView.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/CategoryBottomSheet/CategoryDetailCollectionView/CategoryDetailCultureView.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/CategoryBottomSheet/CategoryDetailCollectionView/CategoryDetailFoodView.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/CategoryBottomSheet/CategoryDetailCollectionView/CategoryDetailPhotoBoothView.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/CategoryBottomSheet/CategoryDetailCollectionView/CategoryDetailShoppingView.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/CategoryBottomSheet/CategoryDetailCollectionView/CategoryDetailView.swift
  Reet-Place/Reet-Place/Screen/Home/ViewController/HomeVC.swift
  Reet-Place/Reet-Place/Screen/Home/ViewModel/CategoryFilterBottomSheetVM.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetBottomSheet/CategoryFilterBottomSheet.swift
Labels: 홈, View, Refactoring, 희재

#101 Refactoring/#81 북마크탭 모두 보기, 가고싶어요, 다녀왔어요 화면 재사용
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkAllVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkHistoryVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkListVC.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkVC.swift
Labels: 북마크, Refactoring, 태현

#104 Fix/#91 회원 탈퇴 시 로그인 타입에 따라 identifier 재발급 처리
  Reet-Place/Reet-Place/Global/Assets/en.lproj/Localizable.strings
  Reet-Place/Reet-Place/Global/Utils/KeychainManager.swift
  Reet-Place/Reet-Place/Screen/Login/ViewModel/LoginVM.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/ViewController/DeleteAccountVC.swift
  Reet-Place/Reet-Place/Screen/MyPage/UserInfo/ViewModel/DeleteAccountVM.swift
Labels: bug🐞, Network, 로그인 / 회원가입

#106 [HOTFIX] : develop 브랜치 빌드 실패 수정
  Reet-Place/Reet-Place/Global/CoreData/CoreDataManager.swift
  Reet-Place/Reet-Place/Global/CoreData/ReetPlace.xcdatamodeld/ReetPlace.xcdatamodel/contents
  Reet-Place/Reet-Place/Global/Enum/CoreDataEntityList.swift
  Reet-Place/Reet-Place/Global/Extension/Array+.swift
Labels: HOTFIX, 희재

#107 [HOTFIX] : CoreData 그룹파일 형성 및 CoreDataManager 파일 이동 반영
  Reet-Place/Reet-Place.xcodeproj/project.pbxproj
  Reet-Place/Reet-Place/Global/CoreData/CategoryFilter+CoreDataClass.swift
  Reet-Place/Reet-Place/Global/CoreData/CategoryFilter+CoreDataProperties.swift
  Reet-Place/Reet-Place/Global/Enum/TabPlaceCategoryList.swift
  Reet-Place/Reet-Place/Global/Protocols/CategoryDetailListAction.swift
  Reet-Place/Reet-Place/Global/Protocols/DetailCategoryChipAction.swift
  Reet-Place/Reet-Place/Screen/BookMark/ViewController/BookmarkListVC.swift
  Reet-Place/Reet-Place/Screen/Home/Model/ModificationCategoryFilterRequestModel.swift
  Reet-Place/Reet-Place/Screen/Shared/View/ReetBottomSheet/CategoryFilterBottomSheet.swift
Labels: HOTFIX, 희재

#110 Feat/#108 GitHub Action을 통한 Build Test 자동화
  .github/workflows/build_test_on_develop.yml
Labels: Feature, 태현
